dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
before_script:
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install libeigen3-dev
script:
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  - dpkg -S /usr/include/boost/version.hpp
  - ls /usr/include/eigen3/
  # Run your build commands next\
  - mkdir src/release
  - cd src/release
  - cmake ..
  - make all -j
  # Test PQ
  - ./pq \
    -t ../../data/audio/audio_base.fvecs  \
    -b ../../data/audio/audio_base.fvecs  \
    -q ../../data/audio/audio_query.fvecs \
    -g ../../data/audio/20_audio_euclid_groundtruth.lshbox \
    --iteration 20 \
    --kmeans_centers 20 \
    --num_codebook 3
  # Test ITQ
  - ./itq \
    -t ../../data/audio/audio_base.fvecs  \
    -b ../../data/audio/audio_base.fvecs  \
    -q ../../data/audio/audio_query.fvecs \
    -g ../../data/audio/20_audio_euclid_groundtruth.lshbox \
    --num_bit 32
  # Test Norm-Range-LSH
  - ./rational_nr \
    -t ../../data/netflix/netflix_base.fvecs  \
    -b ../../data/netflix/netflix_base.fvecs  \
    -q ../../data/netflix/netflix_query.fvecs \
    -g ../../data/netflix/20_netflix_product_groundtruth.lshbox \
    --transformed_dim 1 \
    --num_bit 27\
    --num_sub_data_set 32